---
name: Default

on:
  push:
    paths:
      - "12/**"
      - "13/**"
      - "14/**"
      - "15/**"
      - "16/**"
      - "build.sh"
  pull_request:
    paths:
      - "12/**"
      - "13/**"
      - "14/**"
      - "15/**"
      - "16/**"
      - "build.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./12/
          load: true
          file: ./12/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.4.5
      - name: Inspect
        run: |
          docker image inspect cherts/pg-repack:1.4.5
