name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v1.*"

jobs:
  Build-Pg-12:
    name: Build-Docker-Pg-12
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.4.5
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./12
          file: ./12/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.4.5

  Build-Pg-13:
    name: Build-Docker-Pg-13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.4.6
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./13
          file: ./13/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.4.6

  Build-Pg-14:
    name: Build-Docker-Pg-14
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.4.7
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./14
          file: ./14/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.4.7

  Build-Pg-15:
    name: Build-Docker-Pg-15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.4.8
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./15
          file: ./15/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.4.8

  Build-Pg-16:
    name: Build-Docker-Pg-16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.5.0
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./16
          file: ./16/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.5.0

  Build-Pg-17:
    name: Build-Docker-Pg-17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.5.1
        uses: docker/build-push-action@v6
        env:
          PG_REPACK_VERSION: 1.5.1
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./17
          file: ./17/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.5.1

  Build-Pg-17-152:
    name: Build-Docker-Pg-17-152
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Build and push image cherts/pg-repack:1.5.2
        uses: docker/build-push-action@v6
        env:
          PG_REPACK_VERSION: 1.5.2
        with:
          push: true
          cache-from: type=gha,scope=pg-repack
          cache-to: type=gha,mode=max,scope=pg-repack
          context: ./17
          file: ./17/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: cherts/pg-repack:1.5.2
